@startuml

usecase Программирование
usecase Императивное
usecase Декларативное
usecase Структурное
usecase Неструктурное
usecase Логическое
usecase Процедурное
usecase ОбъектноОриентированное
usecase Функциональное

Программирование --> Императивное
Программирование --> Декларативное
Императивное --> Структурное
Императивное --> Неструктурное
Декларативное --> Логическое
Декларативное --> Функциональное
Структурное --> Процедурное
Структурное --> ОбъектноОриентированное
Структурное ..> Функциональное

@enduml
